### ISSUE TITLE
Can't create a release of image-js

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#222]
When use lactame.com/release the release is updated in github but not avaiable on lactame.com

pm2 grm logs produce an error.
<details>
```
grm-1 Sat, 17 Sep 2016 07:00:17 GMT grm:git getting current HEAD
grm-1 Sat, 17 Sep 2016 07:00:17 GMT grm:repo creating release
grm-1 publish error Error: {"message": "We had issues producing the response to your request. Sorry about that. Please try resubmitting your request and contact us if the problem persists."}
grm-1     at /usr/local/www/sites/www.lactame.com/node/grm/node_modules/octokat/dist/node/request.js:231:19
grm-1     at xhr.onreadystatechange (/usr/local/www/sites/www.lactame.com/node/grm/node_modules/octokat/dist/node/request.js:45:18)
grm-1     at dispatchEvent (/usr/local/www/sites/www.lactame.com/node/grm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
grm-1     at setState (/usr/local/www/sites/www.lactame.com/node/grm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
grm-1     at IncomingMessage.<anonymous> (/usr/local/www/sites/www.lactame.com/node/grm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
grm-1     at emitNone (events.js:91:20)
grm-1     at IncomingMessage.emit (events.js:185:7)
grm-1     at endReadableNT (_stream_readable.js:974:12)
grm-1     at _combinedTickCallback (internal/process/next_tick.js:74:11)
grm-1     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
</details>

**Comment by targos** [comment]
I think it was a problem with the github API. I could do a proper release without any change
